# Change these first
owner: 0xRPC # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Monero Mainnet
    icon: https://assets.coingecko.com/coins/images/69/standard/monero_logo.png
    url: https://xmr.0xrpc.io/get_height

  - name: Ethereum Mainnet
    icon: https://assets.coingecko.com/coins/images/279/standard/ethereum.png
    url: https://0xrpc.io/eth/health

  - name: Ethereum Sepolia Testnet
    icon: https://assets.coingecko.com/coins/images/279/standard/ethereum.png
    url: https://0xrpc.io/sep/health

  - name: Ethereum Hoodi Testnet
    icon: https://assets.coingecko.com/coins/images/279/standard/ethereum.png
    url: https://0xrpc.io/hoodi/health

  - name: Ethereum Classic Mainnet
    icon: https://assets.coingecko.com/coins/images/453/standard/ethereum-classic-logo.png
    url: https://0xrpc.io/etc/health

  - name: ETC Mordor Testnet
    icon: https://assets.coingecko.com/coins/images/453/standard/ethereum-classic-logo.png
    url: https://0xrpc.io/mordor/health

  - name: MintMe.com Mainnet
    icon: https://assets.coingecko.com/coins/images/5127/standard/MINTME_logo.png
    url: https://0xrpc.io/mint/health

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: upptime.0xrpc.io
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: 0xRPC Node Upptime
  introTitle: "**0xRPC Public Nodes Upptime**"
  introMessage: Status page to track 0xRPC public RPC nodes
  navbar:
    - title: Status
      href: /
    - title: Home
      href: https://0xrpc.io

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
